### ISSUE TITLE
No module named 'scipy.fftpack._fftpack'

### ISSUE THREAD

**Issue by echavess** [ROBelgium/MSNoise#208]
Hi all, 

After updating my anaconda (Mac OS, Catalina, 10.15.5) I ran msnoise bugreport to check if eveything was still working fine. I found a compatibility error when trying to import the fft pack from Scipy, called in the api.py script as follows:

`import scipy.fftpack._fftpack as sff`

The error says:

```
 ech@Esteban  ~/Work/CentralPacific_repeaters/Data_processing/Noise  msnoise bugreport
Traceback (most recent call last):
  File "/Users/ech/anaconda3/bin/msnoise", line 6, in <module>
    from msnoise.scripts.msnoise import run
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/scripts/msnoise.py", line 12, in <module>
    from ..api import connect, get_config, update_station, get_logger, get_job_types
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/api.py", line 29, in <module>
    import scipy.fftpack._fftpack as sff
ModuleNotFoundError: No module named 'scipy.fftpack._fftpack'
```

The error is due to the Scipy version that I'm using (1.5.0). Thus (I think) **scipy.fftpack._fftpack** must be replaced with **spicy.fftpack** in the api.py code:

`import scipy.fftpack._fftpack as sff`

with

`import scipy.fftpack as sff`

After replacing this line, the report is free of errors and I get: 

```
Let's Bug Report MSNoise !

************* Computer Report *************
----------------+PYTHON+-------------------
Python:3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)]

This script is at /Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/bugreport.py
```

But when running the msnoise test, I get FAILED (failures=8, errors=2), related the the fftpack. Please find the full test result in my [dropbox](https://www.dropbox.com/s/ap8jn34zestv3yt/msnoise_test.dat?dl=0)

So...Should I downgrade to the 0.14 version of Scipy or is there any fix I'm missing? 

Thanks

**Comment by ThomasLecocq** [comment]
Not missing anything, indeed scipy deprecated stuff. Maybe easier to install msnoise from github masterTomLe 1 août 2020 19:48, Esteban Chaves <notifications@github.com> a écrit :

Hi all,

After updating my anaconda (Mac OS, Catalina, 10.15.5) I ran msnoise bugreport to check if eveything was still working fine. I found a compatibility error when trying to import the fft pack from Scipy, called in the api.py script as follows:

import scipy.fftpack._fftpack as sff

The error says:

 ech@Esteban  ~/Work/CentralPacific_repeaters/Data_processing/Noise  msnoise bugreport

Traceback (most recent call last):

  File "/Users/ech/anaconda3/bin/msnoise", line 6, in <module>

    from msnoise.scripts.msnoise import run

  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/scripts/msnoise.py", line 12, in <module>

    from ..api import connect, get_config, update_station, get_logger, get_job_types

  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/api.py", line 29, in <module>

    import scipy.fftpack._fftpack as sff

ModuleNotFoundError: No module named 'scipy.fftpack._fftpack'



The error is due to the Scipy version that I'm using (1.5.0). Thus (I think) scipy.fftpack._fftpack must be replaced with spicy.fftpack in the api.py code:

import scipy.fftpack._fftpack as sff

with

import scipy.fftpack as sff

After replacing this line, the report is free of errors and I get:

Let's Bug Report MSNoise !



************* Computer Report *************

----------------+PYTHON+-------------------

Python:3.7.3 (default, Mar 27 2019, 16:54:48)

[Clang 4.0.1 (tags/RELEASE_401/final)]



This script is at /Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/bugreport.py



But when running the msnoise test, I get FAILED (failures=8, errors=2), related the the fftpack. Please find the full test result in my dropbox

So...Should I downgrade to the 0.14 version of Scipy or is there any fix I'm missing?

Thanks

**Comment by echavess** [comment]
Alright! Thanks for that quick reply!

**Comment by echavess** [comment]
OK. I just did and got an error: 

```
======================================================================
FAIL: test_030_instrument_response (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/test/tests.py", line 198, in test_013_s03compute_cc
    main()
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/s03compute_no_rotation.py", line 242, in main
    responses = preload_instrument_responses(db, return_format="inventory")
TypeError: __init__() missing 2 required positional arguments: 'networks' and 'source'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/test/tests.py", line 375, in test_030_instrument_response
    self.test_013_s03compute_cc()
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/test/tests.py", line 201, in test_013_s03compute_cc
    self.fail()
AssertionError: None

----------------------------------------------------------------------
Ran 51 tests in 47.425s

FAILED (failures=1, errors=1)
Tests executed in /var/folders/qg/df_zx9nn20z_h_n7df5t9c300000gp/T/tmpdg5njzxf
```

**Comment by ThomasLecocq** [comment]
Msnoise db upgradeTo make sure the db config params are up to dateLe 1 août 2020 20:09, Esteban Chaves <notifications@github.com> a écrit :
OK. I just did and got an error:
======================================================================
FAIL: test_030_instrument_response (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/test/tests.py", line 198, in test_013_s03compute_cc
    main()
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/s03compute_no_rotation.py", line 242, in main
    responses = preload_instrument_responses(db, return_format="inventory")
TypeError: __init__() missing 2 required positional arguments: 'networks' and 'source'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/test/tests.py", line 375, in test_030_instrument_response
    self.test_013_s03compute_cc()
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/test/tests.py", line 201, in test_013_s03compute_cc
    self.fail()
AssertionError: None

----------------------------------------------------------------------
Ran 51 tests in 47.425s

FAILED (failures=1, errors=1)
Tests executed in /var/folders/qg/df_zx9nn20z_h_n7df5t9c300000gp/T/tmpdg5njzxf

**Comment by SeismoFelix** [comment]
Hi!

I installed the latest stable version of [msnoise ](http://msnoise.org/doc/installation.html) and I got the same error reported in this issue 4 years ago:

    import scipy.fftpack._fftpack as sff
ModuleNotFoundError: No module named 'scipy.fftpack._fftpack'

The scipy version installed by default following the installation instructions is:

```
>>> import scipy as sp
>>> sp.__version__
'1.13.1'
```

I have seen there is a conditional that ensures this error may not happen:

```
if scipy.__version__ < "1.4.0":
    import scipy.fftpack as sf
    from scipy.fftpack.helper import next_fast_len
    import scipy.fftpack._fftpack as sff
    #import scipy.fftpack as sff
else:
    import scipy.fft as sf
    from scipy.fft import next_fast_len
```

and version '1.13.1' is more recent than '1.4.1'.  I wonder if it is more reccommended to install the latest version ( MSNoise 2.0), although is not the stable one. 

Thanks for your help.

**Comment by rjh099** [comment]
I have struggled with this for a while, I wonder if the bug may be fixed for the new stable version..
