### ISSUE TITLE
Possible Stacking and MWCS Issue?

### ISSUE THREAD

**Issue by yadavapersad** [ROBelgium/MSNoise#225]
Good-day, 

I am a first time user of msnosise. I am able to follow all the steps as instructed in the msnoise manual and everything runs and works.  However, I have 2 concerns regarding the Stacking and MWCS steps. 

1) Stacking - when I run msnoise stack -r and msnoise stack -m, it returns **"There are STACKS jobs for some days to recompute for TR.SVGT:TR.SVWL".** This is just 1 example of a particular station pair. It does this for 28 station pairs. I currently have 8 stations in my database. Is this what should be expected?

2) compute_mwcs - when I execute the command to compute_mwcs, it also returns, "There are MWCS jobs for some days to recompute for TR.SVT:TR.SVWL" and it also does this for 28 station pairs. However, on the msnoise configuration page it tells me 98% completed for this action and not 100% as these 28 jobs remain "Todo". 
I understand that these are the REF station pairs but in the archive August 2020 indicated that the REF jobs are no longer used and will be removed in later versions. 

I am currently using Python version 3.7.3 and msnoise version 1.6.1. 

I have attached the files for your viewing. 

Much thanks, 
Yadava Persad 
[msnoise_mwcs.txt](https://github.com/ROBelgium/MSNoise/files/6709783/msnoise_mwcs.txt)
[msnoise_stacks.txt](https://github.com/ROBelgium/MSNoise/files/6709785/msnoise_stacks.txt)

**Comment by ThomasLecocq** [comment]
Hi,
1. yes, it does stacks sequentially indeed
2. yes, the REF jobs are left-overs from the past, they will no longer be existing in the next release. They were used to flag the fact that the REF changed, and so MWCS should automatically be re-done on ALL data since it changed. But this is no longer the case, as sometimes you just want to change the REF and move on with this, without reprocessing all the data.
