### ISSUE TITLE
filters and sampling rate question

### ISSUE THREAD

**Issue by sujan1746** [ROBelgium/MSNoise#232]
Hi, I have some questions and I think I need to know necessarily.
So, if it is possible, could you please let me know about msnoise in detail.

1.  Multiple filters
The step is Add filter ==> Compute_cc right?
But when I add multiple filters and compute_cc, there is no significant problems, but it takes too much time.
With one filter, compute_cc was completed in 6 hours, but with 10 filters, over 12 hours, it still 36%. 
Also, it frequently stopped with below errors.
![image](https://user-images.githubusercontent.com/89066297/130552517-1fa41069-2ae7-4891-9038-c7874d6e7493.png)
So I wonder is it possible to add one filter in a broad corner frequency, compute_cc, change the filter to multiple filters, and do next steps?
I mean, **is it possible to change or add filters after compute_cc?**

2. Sampling rate
In configuration (parameters), there is only cc_sampling_rate but no 'sampling rate'.
When I change parameters and do steps (scan_archive, new_jobs, compute_cc...), I can see sampling rate is 200 in data_availability tap.
**Is there any way to change sampling rate?** (especially before starting scanning archive)
This is because sometimes I have to change the sampling rate.

**Comment by ThomasLecocq** [comment]
1. the preprocessing is unique for all filters, but CC computation time scales linearly with the number of filters, there is nothing you can change to it. The error you get is because you're using sqlite database, with mutlithread call `-t N`, which, in the documentation, is not recommended (because sqlite doesn't support concurrent writes). About the order of operations: technically yes, but it will require YOU to do some coding/copy-paste:

- define broadband filter 01
- compute CC
- modify filter 01 to be narrow band 1
- compute MWCS
- compute DTT
- move MWCS/01 -> MWCS/my01
- move DTT/01 -> DTT/my01
- reset MWCS jobs
- modify filter 01 to be narrow band 2
- compute MWCS
- compute DTT
- move MWCS/01 -> MWCS/my02
- move DTT/01 -> DTT/my02
- etc ...

2. data_availability lists what's in your files; the cc_sampling_rate is the sps you want for the CC output, which has to be lower or equal to your smaller files' sampling_rate, and twice as large as the higher filter bound you defining. In NO way you can change the sps of the original files, that's not the goal of msnoise.

**Comment by sujan1746** [comment]
Thank you so much for your help.

1) I just want to check. So.. I do not need to reset CC -a before modify filter, is it right?

2) If the cc_sampling_rate is twice as large as the highest filter I defined, then do I have to change the cc_sampling_rate(in config) before modifying filter?

**Comment by ThomasLecocq** [comment]
> 1. I just want to check. So.. I do not need to reset CC -a before modify filter, is it right?
no, just follow what I wrote

> 2. If the cc_sampling_rate is twice as large as the highest filter I defined, then do I have to change the cc_sampling_rate(in config) before modifying filter?
you have to define it once, an all your computed CC will have this sampling rate, even if later you change the filter high bound to a smaller value, that's no problem.

**Comment by sujan1746** [comment]
I see.
Your solutions have been very helpful for me.
Thank you so much!!

**Comment by ThomasLecocq** [comment]
note, for MSNoise2 (in dev), I'm considering allowing reversing the filter logic, to match what you want to do: broadband filter and then narrow MWCS. Work in progres...... :-)

**Comment by sujan1746** [comment]
I got it. That's a good news! I'm looking forward to use it :)
